### ISSUE TITLE
Unit state problem

### ISSUE THREAD

**Issue by cmurga4960** [ARL-UTEP-OC/emubox#42]
This problem concerns the workshop-manager.  Once a client disconnects from the remote session, the unit state is restarted.  However if the client shuts down the VM (e.g. runs 'init 0' in Kali) the unit will not reset.  This may cause problems for large scale events.

**Comment by FoxHoundOps** [comment]
Sounds like an interesting situation. Perhaps the manager could have some knowledge of which workshops are running and it can check to see if machines are powered off that were once running (should be running)? So it could start it back up? Or if this should a part of setting up the virtual machines, like preventing a user from shutting it down? Should definitely explore this.
